version: '3'

services:
  drupal:
    image: drupal:8-apache
    ports:
      - 80:80
    volumes:
      - /var/www/html/modules
      - /var/www/html/profiles
      - /var/www/html/themes
      - /var/www/html/sites
    networks:
      - app
 
  postgres:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: example
    networks:
      - app

networks:
  app:
    driver: bridge